Create A Record for grafana
nycmeshnet/nycmesh-dns pull request #73
Opened 2024-07-27 16:55 UTC by WillNilges

Creates a new A record for the current(?) grafana instance. This should make it easier to find and use for volunteers (such as myself 🙃)

2024-07-27 17:35 UTC, OlivierMorf commented
why under Willard?

We need a section "Mesh services".

2024-07-27 17:40 UTC, OlivierMorf commented
in fact should be with thet unifi, UISP, etc...  records, no ?

2024-07-27 18:27 UTC, OlivierMorf commented
https://wiki.mesh.nycmesh.net/books/6-services-software/page/alerting-and-monitoring-system

2024-07-27 20:58 UTC, james-otten approved these changes

2024-07-28 04:45 UTC, danielhmetro requested changes
I agree that this service should be added under
; Allocated domains

2024-07-29 16:16 UTC, danielhmetro approved these changes

2024-07-29 16:17 UTC, merged